export const cocktailRecipes = [
  {
    cocktailName: "Pornstar Martini",
    ingredients: ["Vodka", "passion fruit liqueur", "passion fruit puree", "lime juice", "simple syrup", "vanilla extract", "champagne"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a martini glass.<br> Serve with a champagne shot on the side.",
    image: "images/pornstar-martini.jpg",
    alt: "a photo of a Pornstar Martini",
  },
  {
    cocktailName: "Gin Basil Smash",
    ingredients: ["Gin", "lemon juice", "simple syrup", "basil leaves"],
    isShaken: true,
    instructions: "Muddle the basil leaves on the shaker. Shake all ingredients with ice and double strain into a rocks glass filled with ice.",
    image: "images/gin-basil-smash.jpg",
    alt: "a photo of a Gin Basil Smash",
  },
  {
    cocktailName: "Espresso Martini",
    ingredients: ["Vodka", "coffee liqueur", "espresso"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a martini glass.",
    image: "images/espresso-martini.jpg",
    alt: "a photo of an Espresso Martini",
  },
  {
    cocktailName: "Ramos Gin Fizz",
    ingredients: ["Gin", "lemon juice", "lime juice", "simple syrup", "heavy cream", "egg white", "orange flower water"],
    isShaken: true,
    instructions: "Dry shake, then shake again with ice and strain into a highball glass.",
    image: "images/ramos-gin-fizz.jpg",
    alt: "a photo of a Ramos Gin Fizz",
  },
  {
    cocktailName: "Daiquiri",
    ingredients: ["Rum", "lime juice", "simple syrup"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a chilled coupe glass.",
    image: "images/strawberry-frozen-daiquiri.jpg",
    alt: "a photo of a frozen strawberry Daiquiri",
  },
  {
    cocktailName: "Margarita",
    ingredients: ["Tequila", "lime juice", "triple sec"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a salt-rimmed margarita glass.",
    image: "images/margarita2.jpg",
    alt: "a photo of a Margarita",
  },
  {
    cocktailName: "Sex on the Beach",
    ingredients: ["Vodka", "peach schnapps", "cranberry juice", "orange juice"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a highball glass filled with ice.",
    image: "images/sex-on-the-beach.jpg",
    alt: "a photo of a Sex on the Beach",
  },
  {
    cocktailName: "Penicillin",
    ingredients: ["Whisky", "lemon juice", "honey syrup", "fresh ginger"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a rocks glass filled with ice.",
    image: "images/penicillin.jpg",
    alt: "a photo of a Penicillin",
  },
  {
    cocktailName: "Old Cuban",
    ingredients: ["Rum", "champagne", "simple syrup", "angostura bitters", "mint leaves"],
    isShaken: true,
    instructions: "Shake an aged rum, syrup, bitters, and mint.<br> Strain into a flute, top with champagne.",
    image: "images/old-cuban.jpg",
    alt: "a photo of an Old Cuban",
  },
  {
    cocktailName: "Moscow Mule",
    ingredients: ["Vodka", "ginger beer", "lime juice"],
    isShaken: false,
    instructions: "Build in a copper mug with ice, stir, and garnish with a lime wheel.",
    image: "images/moscow-mule.jpg",
    alt: "a photo of a Moscow Mule",
  },
  {
    cocktailName: "Caipirinha",
    ingredients: ["Cachaça", "lime", "sugar"],
    isShaken: false,
    instructions: "Muddle one whole lime and sugar in a glass, fill with ice, and add cachaça.<br> Stir well.",
    image: "images/caipirinha.jpg",
    alt: "a photo of a Caipirinha",
  },
  {
    cocktailName: "Negroni",
    ingredients: ["Gin", "vermouth", "Campari"],
    isShaken: false,
    instructions: "Stir all ingredients with ice and strain into a rocks glass filled with ice.",
    image: "images/negroni.jpg",
    alt: "a photo of a Negroni",
  },
  {
    cocktailName: "Paloma",
    ingredients: ["Tequila", "grapefruit soda", "lime juice", "simple syrup"],
    isShaken: false,
    instructions: "Build in a highball glass with ice, stir, and garnish with a grapefruit slice.",
    image: "images/paloma.jpg",
    alt: "a photo of a Paloma",
  },
  {
    cocktailName: "Clover Club",
    ingredients: ["Gin", "raspberry syrup", "lemon juice", "egg white"],
    isShaken: true,
    instructions: "Dry shake, then shake again with ice and strain into a coupe glass.",
    image: "images/clover-club.jpg",
    alt: "a photo of a Clover Club",
  },
  {
    cocktailName: "Bramble",
    ingredients: ["Gin", "blackberry liqueur", "lemon juice", "simple syrup"],
    isShaken: true,
    instructions: "Shake gin, lemon juice, and syrup, strain into a rocks glass over crushed ice, and drizzle blackberry liqueur on top.",
    image: "images/bramble.jpg",
    alt: "a photo of a Bramble",
  },
  {
    cocktailName: "Mai Tai",
    ingredients: ["Rum", "lime juice", "orgeat syrup", "orange liqueur"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into an old-fashioned glass filled with crushed ice.<br> Garnish with a mint sprig.",
    image: "images/maitai2.jpg",
    alt: "a photo of a Mai Tai",
  },
  {
    cocktailName: "Cantaritos",
    ingredients: ["Tequila", "grapefruit juice", "orange juice", "lime juice", "simple syrup", "soda water"],
    isShaken: false,
    instructions: "Build in a cantaritos mug with ice. Stir and top with soda water.",
    image: "images/cantaritos.jpg",
    alt: "a photo of a Cantaritos",
  },
  {
    cocktailName: "The Last Word",
    ingredients: ["Gin", "green chartreuse", "maraschino liqueur", "lime juice"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a chilled coupe glass.",
    image: "images/the-last-word.jpg",
    alt: "a photo of The Last Word",
  },
  {
    cocktailName: "Jungle Bird",
    ingredients: ["Rum", "pineapple juice", "Campari", "simple syrup", "lime juice"],
    isShaken: false,
    instructions: "Build in a highball glass with ice. Stir and garnish with a pineapple leaf.",
    image: "images/jungle-bird.jpg",
    alt: "a photo of a Jungle Bird",
  },
  {
    cocktailName: "White Lady",
    ingredients: ["Gin", "triple sec", "lemon juice", "simple syrup", "egg white"],
    isShaken: true,
    instructions: "Dry shake, then shake again with ice and strain into a chilled coupe glass.",
    image: "images/white-lady.jpg",
    alt: "a photo of a White Lady",
  },
  {
    cocktailName: "Whiskey Sour",
    ingredients: ["Bourbon", "lemon juice", "simple syrup", "egg white"],
    isShaken: true,
    instructions: "Dry shake, then shake again with ice and strain into a rocks glass filled with ice.",
    image: "images/whiskey-sour.jpg",
    alt: "a photo of a Whiskey Sour",
  },
  {
    cocktailName: "Aperol Spritz",
    ingredients: ["Aperol", "prosecco", "soda water", "orange slice"],
    isShaken: false,
    instructions: "Build in a wine glass with ice. Top with prosecco and soda water. Garnish with an orange slice.",
    image: "images/aperol-spritz.jpg",
    alt: "a photo of an Aperol Spritz",
  },
  {
    cocktailName: "Cosmopolitan",
    ingredients: ["Vodka", "triple sec", "cranberry juice", "lime juice"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a chilled martini glass.",
    image: "images/cosmopolitan.jpg",
    alt: "a photo of a Cosmopolitan",
  },
  {
    cocktailName: "Mojito",
    ingredients: ["Rum", "lime", "simple syrup", "mint leaves", "soda water"],
    isShaken: false,
    instructions: "Muddle lime and mint in a glass. Add rum, simple syrup, and ice. Top with soda water and stir.",
    image: "images/mojito.jpg",
    alt: "a photo of a Mojito",
  },
  {
    cocktailName: "Old Fashioned",
    ingredients: ["Bourbon", "sugar cube", "Angostura bitters", "orange twist"],
    isShaken: false,
    instructions: "Muddle sugar cube with bitters in a glass. Add a few drops of water and stir. Add bourbon and ice. Garnish with an orange twist.",
    image: "images/Old-fashioned.jpg",
    alt: "a photo of an Old Fashioned",
  },
  {
    cocktailName: "Piña Colada",
    ingredients: ["Rum", "coconut cream", "pineapple juice"],
    isShaken: false,
    instructions: "Blend all ingredients with ice until smooth. Pour into a chilled hurricane glass.",
    image: "images/pina-colada.jpg",
    alt: "a photo of a Pina Colada",
  },
  {
    cocktailName: "New York Sour",
    ingredients: ["Bourbon", "lemon juice", "simple syrup", "red wine"],
    isShaken: true,
    instructions: "Shake bourbon, lemon juice, and simple syrup with ice. Strain into a rocks glass filled with ice. Float red wine on top.",
    image: "images/new-york-sour.jpg",
    alt: "a photo of a New York Sour",
  },
  {
    cocktailName: "Martinez",
    ingredients: ["Gin", "sweet vermouth", "maraschino liqueur", "orange bitters"],
    isShaken: true,
    instructions: "Stir all ingredients with ice and strain into a chilled coupe glass.",
    image: "images/martinez.jpg",
    alt: "a photo of a Martinez",
  },
  {
    cocktailName: "Naked & Famous",
    ingredients: ["Aperol", "Mezcal", "yellow chartreuse", "lime juice"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a chilled coupe glass.",
    image: "images/naked&famous.jpg",
    alt: "a photo of a Naked & Famous",
  },
  {
    cocktailName: "Vieux Carré",
    ingredients: ["Whisky", "Cognac", "sweet vermouth", "Benedictine", "Angostura bitters", "Peychaud's bitters"],
    isShaken: false,
    instructions: "Stir all ingredients with ice and strain into a rocks glass filled with ice.",
    image: "images/vieux-carre.jpg",
    alt: "a photo of a Vieux Carré",
  },
  {
    cocktailName: "Macunaíma",
    ingredients: ["Cachaça", "lemon juice", "sugar", "fernet liqueur"],
    isShaken: true,
    instructions: "Shake all ingredients with ice and strain into a chilled a glass.",
    image: "images/macunaima.jpg",
    alt: "a photo of Macunaíma",
  },
];
